console.log("======== MENU ========")
console.log("1 - Listar Clientes")
console.log("2 - Cadastrar Cliente")
console.log("3 - Editar Cliente")
console.log("4 - Remover Cliente")
console.log("0 - Sair do sistema")
console.log("======================")
console.log("Opção: __")
console.log("======================")
